version: '3.9'

services:

  app:
    build: . .
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app
    restart: always

  nginx:
    image: nginx:1.20.2-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    restart: always
